version: '3.8'

services:
  app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      # 실제 DB 연동은 필수가 아니지만, 컨테이너 간 네트워크 구조를 드러내기 위해 설정
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: arom
      DB_PASSWORD: 1234
      DB_NAME: korea

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: korea
      MYSQL_USER: arom
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
